apiVersion: v1
kind: Service
metadata:
  name: device-service-serv
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
spec:
  selector:
    app: {{.Values.deployment.app}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.deployment.port}}
      protocol: TCP