apiVersion: v1
kind: Service
metadata:
  name: device-service-serv
spec:
  selector:
    app: {{.Values.deployment.app}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.deployment.port}}
      protocol: TCP