tenant-id:
  attribute-key: ${TENANT_ID_ATTRIBUTE_KEY:tenant-id}
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:device-service}
      autoIndexCreation: true
  cloud:
    stream:
      bindings:
        input:
          destination:
             er: ${DEVICE_DATA_SUBSCRIPTION:device-service-sub}
             es:
               add: ${PIPELINE_ADDING_SUBSCRIPTION:device-pipeline-add-sub}
               drop: ${PIPELINE_DELETING_SUBSCRIPTION:device-pipeline-drop-sub}
    gcp:
      project-id: ${PROJECT_ID:single-system}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    producer:
      data-for-save-topic: ${KAFKA_PRODUCER_TOPIC_FOR_SAVE:device-data-for-save}
      device-sending-data-topic: ${DEVICE_SENDING_DATA_TOPIC:device-sending-data}
      port-sending-data-topic: ${PORT_SENDING_DATA_TOPIC:port-sending-data}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${SERVER_PORT:8080}

execution-service:
  address:
    host: ${EXECUTION_SERVICE_ADDRESS_HOST:localhost}
    port: ${EXECUTION_SERVICE_ADDRESS_PORT:9099}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE_ENDPOINTS:*}
  info:
    git:
      enabled: true
  server:
    port: ${ACTUATOR_PORT:8090}
