spring:
  data:
    mongodb:
      uri: ${URI:mongodb://localhost:27017}
      database: ${DATABASE:device-service}
  cloud:
    stream:
      bindings:
        input:
          destination: ${SUBSCRIPTION:device-service-sub}
    gcp:
      project-id: ${PROJECT_ID:single-system}
server:
  port: ${PORT:9093}

