tenant-id:
  attribute-key: ${TENANT_ID_ATTRIBUTE_KEY:tenant-id}
spring:
  data:
    mongodb:
      uri: ${URI:mongodb://localhost:27017}
      database: ${DATABASE:device-service}
  cloud:
    stream:
      bindings:
        input:
          destination:
             er: ${SUBSCRIPTION:device-service-sub}
             es: ${SUBSCRIPTION:device-pipeline-sub}
    gcp:
      project-id: ${PROJECT_ID:single-system}
  kafka:
    producer:
      for-save-topic: ${KAFKA_PRODUCER_TOPIC_FOR_SAVE:device-data-for-save}
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${PORT:8080}

execution-service:
  address:
    host: ${EXECUTION_SERVICE_ADDRESS_HOST:localhost}
    port: ${EXECUTION_SERVICE_ADDRESS_PORT:9099}
