// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/datetime.proto

package com.google.type;

public interface TimeZoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.type.TimeZone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * IANA Time Zone Database time zone, e.g. "America/New_York".
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * IANA Time Zone Database time zone, e.g. "America/New_York".
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Optional. IANA Time Zone Database version number, e.g. "2019a".
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * Optional. IANA Time Zone Database version number, e.g. "2019a".
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
