// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/services/pipelines-service.proto
package com.ynero.ss.device_service.proto.main.java;
import com.ynero.ss.device_service.proto.main.java.PipelinesMessage;

public final class PipelinesService {
  private PipelinesService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&proto/services/pipelines-service.proto" +
      "\032\033google/protobuf/empty.proto\032&proto/mes" +
      "sages/pipelines-message.proto2F\n\017Pipelin" +
      "eRequest\0223\n\007receive\022\016.PipelineQuery\032\026.go" +
      "ogle.protobuf.Empty\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          PipelinesMessage.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    PipelinesMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
