package com.ynero.ss.device_service.proto.main.java;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/messages/pipelines-message.proto

public final class PipelinesMessage {
  private PipelinesMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PipelineDevicesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PipelineDevices)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pipelineId = 1;</code>
     */
    java.lang.String getPipelineId();
    /**
     * <code>string pipelineId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPipelineIdBytes();

    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    java.util.List<PipelinesMessage.DeviceData> 
        getDevicesDataList();
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    PipelinesMessage.DeviceData getDevicesData(int index);
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    int getDevicesDataCount();
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    java.util.List<? extends PipelinesMessage.DeviceDataOrBuilder> 
        getDevicesDataOrBuilderList();
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    PipelinesMessage.DeviceDataOrBuilder getDevicesDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PipelineDevices}
   */
  public  static final class PipelineDevices extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PipelineDevices)
      PipelineDevicesOrBuilder {
    // Use PipelineDevices.newBuilder() to construct.
    private PipelineDevices(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PipelineDevices() {
      pipelineId_ = "";
      devicesData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PipelineDevices(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pipelineId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                devicesData_ = new java.util.ArrayList<PipelinesMessage.DeviceData>();
                mutable_bitField0_ |= 0x00000002;
              }
              devicesData_.add(
                  input.readMessage(PipelinesMessage.DeviceData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          devicesData_ = java.util.Collections.unmodifiableList(devicesData_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PipelinesMessage.internal_static_PipelineDevices_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PipelinesMessage.internal_static_PipelineDevices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PipelinesMessage.PipelineDevices.class, PipelinesMessage.PipelineDevices.Builder.class);
    }

    private int bitField0_;
    public static final int PIPELINEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object pipelineId_;
    /**
     * <code>string pipelineId = 1;</code>
     */
    public java.lang.String getPipelineId() {
      java.lang.Object ref = pipelineId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipelineId_ = s;
        return s;
      }
    }
    /**
     * <code>string pipelineId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPipelineIdBytes() {
      java.lang.Object ref = pipelineId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipelineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICESDATA_FIELD_NUMBER = 2;
    private java.util.List<PipelinesMessage.DeviceData> devicesData_;
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    public java.util.List<PipelinesMessage.DeviceData> getDevicesDataList() {
      return devicesData_;
    }
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    public java.util.List<? extends PipelinesMessage.DeviceDataOrBuilder> 
        getDevicesDataOrBuilderList() {
      return devicesData_;
    }
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    public int getDevicesDataCount() {
      return devicesData_.size();
    }
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    public PipelinesMessage.DeviceData getDevicesData(int index) {
      return devicesData_.get(index);
    }
    /**
     * <code>repeated .DeviceData devicesData = 2;</code>
     */
    public PipelinesMessage.DeviceDataOrBuilder getDevicesDataOrBuilder(
        int index) {
      return devicesData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPipelineIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pipelineId_);
      }
      for (int i = 0; i < devicesData_.size(); i++) {
        output.writeMessage(2, devicesData_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPipelineIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pipelineId_);
      }
      for (int i = 0; i < devicesData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, devicesData_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PipelinesMessage.PipelineDevices)) {
        return super.equals(obj);
      }
      PipelinesMessage.PipelineDevices other = (PipelinesMessage.PipelineDevices) obj;

      boolean result = true;
      result = result && getPipelineId()
          .equals(other.getPipelineId());
      result = result && getDevicesDataList()
          .equals(other.getDevicesDataList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PIPELINEID_FIELD_NUMBER;
      hash = (53 * hash) + getPipelineId().hashCode();
      if (getDevicesDataCount() > 0) {
        hash = (37 * hash) + DEVICESDATA_FIELD_NUMBER;
        hash = (53 * hash) + getDevicesDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PipelinesMessage.PipelineDevices parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PipelinesMessage.PipelineDevices parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PipelinesMessage.PipelineDevices parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PipelinesMessage.PipelineDevices parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PipelinesMessage.PipelineDevices prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PipelineDevices}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PipelineDevices)
        PipelinesMessage.PipelineDevicesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PipelinesMessage.internal_static_PipelineDevices_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PipelinesMessage.internal_static_PipelineDevices_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PipelinesMessage.PipelineDevices.class, PipelinesMessage.PipelineDevices.Builder.class);
      }

      // Construct using PipelinesMessage.PipelineDevices.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDevicesDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        pipelineId_ = "";

        if (devicesDataBuilder_ == null) {
          devicesData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          devicesDataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PipelinesMessage.internal_static_PipelineDevices_descriptor;
      }

      public PipelinesMessage.PipelineDevices getDefaultInstanceForType() {
        return PipelinesMessage.PipelineDevices.getDefaultInstance();
      }

      public PipelinesMessage.PipelineDevices build() {
        PipelinesMessage.PipelineDevices result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PipelinesMessage.PipelineDevices buildPartial() {
        PipelinesMessage.PipelineDevices result = new PipelinesMessage.PipelineDevices(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.pipelineId_ = pipelineId_;
        if (devicesDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            devicesData_ = java.util.Collections.unmodifiableList(devicesData_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.devicesData_ = devicesData_;
        } else {
          result.devicesData_ = devicesDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PipelinesMessage.PipelineDevices) {
          return mergeFrom((PipelinesMessage.PipelineDevices)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PipelinesMessage.PipelineDevices other) {
        if (other == PipelinesMessage.PipelineDevices.getDefaultInstance()) return this;
        if (!other.getPipelineId().isEmpty()) {
          pipelineId_ = other.pipelineId_;
          onChanged();
        }
        if (devicesDataBuilder_ == null) {
          if (!other.devicesData_.isEmpty()) {
            if (devicesData_.isEmpty()) {
              devicesData_ = other.devicesData_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDevicesDataIsMutable();
              devicesData_.addAll(other.devicesData_);
            }
            onChanged();
          }
        } else {
          if (!other.devicesData_.isEmpty()) {
            if (devicesDataBuilder_.isEmpty()) {
              devicesDataBuilder_.dispose();
              devicesDataBuilder_ = null;
              devicesData_ = other.devicesData_;
              bitField0_ = (bitField0_ & ~0x00000002);
              devicesDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDevicesDataFieldBuilder() : null;
            } else {
              devicesDataBuilder_.addAllMessages(other.devicesData_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PipelinesMessage.PipelineDevices parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PipelinesMessage.PipelineDevices) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object pipelineId_ = "";
      /**
       * <code>string pipelineId = 1;</code>
       */
      public java.lang.String getPipelineId() {
        java.lang.Object ref = pipelineId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pipelineId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pipelineId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPipelineIdBytes() {
        java.lang.Object ref = pipelineId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pipelineId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pipelineId = 1;</code>
       */
      public Builder setPipelineId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pipelineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pipelineId = 1;</code>
       */
      public Builder clearPipelineId() {
        
        pipelineId_ = getDefaultInstance().getPipelineId();
        onChanged();
        return this;
      }
      /**
       * <code>string pipelineId = 1;</code>
       */
      public Builder setPipelineIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pipelineId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<PipelinesMessage.DeviceData> devicesData_ =
        java.util.Collections.emptyList();
      private void ensureDevicesDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          devicesData_ = new java.util.ArrayList<PipelinesMessage.DeviceData>(devicesData_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PipelinesMessage.DeviceData, PipelinesMessage.DeviceData.Builder, PipelinesMessage.DeviceDataOrBuilder> devicesDataBuilder_;

      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public java.util.List<PipelinesMessage.DeviceData> getDevicesDataList() {
        if (devicesDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(devicesData_);
        } else {
          return devicesDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public int getDevicesDataCount() {
        if (devicesDataBuilder_ == null) {
          return devicesData_.size();
        } else {
          return devicesDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public PipelinesMessage.DeviceData getDevicesData(int index) {
        if (devicesDataBuilder_ == null) {
          return devicesData_.get(index);
        } else {
          return devicesDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder setDevicesData(
          int index, PipelinesMessage.DeviceData value) {
        if (devicesDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicesDataIsMutable();
          devicesData_.set(index, value);
          onChanged();
        } else {
          devicesDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder setDevicesData(
          int index, PipelinesMessage.DeviceData.Builder builderForValue) {
        if (devicesDataBuilder_ == null) {
          ensureDevicesDataIsMutable();
          devicesData_.set(index, builderForValue.build());
          onChanged();
        } else {
          devicesDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder addDevicesData(PipelinesMessage.DeviceData value) {
        if (devicesDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicesDataIsMutable();
          devicesData_.add(value);
          onChanged();
        } else {
          devicesDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder addDevicesData(
          int index, PipelinesMessage.DeviceData value) {
        if (devicesDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicesDataIsMutable();
          devicesData_.add(index, value);
          onChanged();
        } else {
          devicesDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder addDevicesData(
          PipelinesMessage.DeviceData.Builder builderForValue) {
        if (devicesDataBuilder_ == null) {
          ensureDevicesDataIsMutable();
          devicesData_.add(builderForValue.build());
          onChanged();
        } else {
          devicesDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder addDevicesData(
          int index, PipelinesMessage.DeviceData.Builder builderForValue) {
        if (devicesDataBuilder_ == null) {
          ensureDevicesDataIsMutable();
          devicesData_.add(index, builderForValue.build());
          onChanged();
        } else {
          devicesDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder addAllDevicesData(
          java.lang.Iterable<? extends PipelinesMessage.DeviceData> values) {
        if (devicesDataBuilder_ == null) {
          ensureDevicesDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, devicesData_);
          onChanged();
        } else {
          devicesDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder clearDevicesData() {
        if (devicesDataBuilder_ == null) {
          devicesData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          devicesDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public Builder removeDevicesData(int index) {
        if (devicesDataBuilder_ == null) {
          ensureDevicesDataIsMutable();
          devicesData_.remove(index);
          onChanged();
        } else {
          devicesDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public PipelinesMessage.DeviceData.Builder getDevicesDataBuilder(
          int index) {
        return getDevicesDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public PipelinesMessage.DeviceDataOrBuilder getDevicesDataOrBuilder(
          int index) {
        if (devicesDataBuilder_ == null) {
          return devicesData_.get(index);  } else {
          return devicesDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public java.util.List<? extends PipelinesMessage.DeviceDataOrBuilder> 
           getDevicesDataOrBuilderList() {
        if (devicesDataBuilder_ != null) {
          return devicesDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(devicesData_);
        }
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public PipelinesMessage.DeviceData.Builder addDevicesDataBuilder() {
        return getDevicesDataFieldBuilder().addBuilder(
            PipelinesMessage.DeviceData.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public PipelinesMessage.DeviceData.Builder addDevicesDataBuilder(
          int index) {
        return getDevicesDataFieldBuilder().addBuilder(
            index, PipelinesMessage.DeviceData.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceData devicesData = 2;</code>
       */
      public java.util.List<PipelinesMessage.DeviceData.Builder> 
           getDevicesDataBuilderList() {
        return getDevicesDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PipelinesMessage.DeviceData, PipelinesMessage.DeviceData.Builder, PipelinesMessage.DeviceDataOrBuilder> 
          getDevicesDataFieldBuilder() {
        if (devicesDataBuilder_ == null) {
          devicesDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PipelinesMessage.DeviceData, PipelinesMessage.DeviceData.Builder, PipelinesMessage.DeviceDataOrBuilder>(
                  devicesData_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          devicesData_ = null;
        }
        return devicesDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PipelineDevices)
    }

    // @@protoc_insertion_point(class_scope:PipelineDevices)
    private static final PipelinesMessage.PipelineDevices DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PipelinesMessage.PipelineDevices();
    }

    public static PipelinesMessage.PipelineDevices getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PipelineDevices>
        PARSER = new com.google.protobuf.AbstractParser<PipelineDevices>() {
      public PipelineDevices parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PipelineDevices(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PipelineDevices> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PipelineDevices> getParserForType() {
      return PARSER;
    }

    public PipelinesMessage.PipelineDevices getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeviceDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceId = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string port = 2;</code>
     */
    java.lang.String getPort();
    /**
     * <code>string port = 2;</code>
     */
    com.google.protobuf.ByteString
        getPortBytes();

    /**
     * <code>string value = 3;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code DeviceData}
   */
  public  static final class DeviceData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeviceData)
      DeviceDataOrBuilder {
    // Use DeviceData.newBuilder() to construct.
    private DeviceData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceData() {
      deviceId_ = "";
      port_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DeviceData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              port_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PipelinesMessage.internal_static_DeviceData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PipelinesMessage.internal_static_DeviceData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PipelinesMessage.DeviceData.class, PipelinesMessage.DeviceData.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string deviceId = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private volatile java.lang.Object port_;
    /**
     * <code>string port = 2;</code>
     */
    public java.lang.String getPort() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        port_ = s;
        return s;
      }
    }
    /**
     * <code>string port = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPortBytes() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 3;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getPortBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, port_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getPortBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, port_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PipelinesMessage.DeviceData)) {
        return super.equals(obj);
      }
      PipelinesMessage.DeviceData other = (PipelinesMessage.DeviceData) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getPort()
          .equals(other.getPort());
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PipelinesMessage.DeviceData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PipelinesMessage.DeviceData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PipelinesMessage.DeviceData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PipelinesMessage.DeviceData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PipelinesMessage.DeviceData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PipelinesMessage.DeviceData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PipelinesMessage.DeviceData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PipelinesMessage.DeviceData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PipelinesMessage.DeviceData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PipelinesMessage.DeviceData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PipelinesMessage.DeviceData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceData)
        PipelinesMessage.DeviceDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PipelinesMessage.internal_static_DeviceData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PipelinesMessage.internal_static_DeviceData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PipelinesMessage.DeviceData.class, PipelinesMessage.DeviceData.Builder.class);
      }

      // Construct using PipelinesMessage.DeviceData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        port_ = "";

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PipelinesMessage.internal_static_DeviceData_descriptor;
      }

      public PipelinesMessage.DeviceData getDefaultInstanceForType() {
        return PipelinesMessage.DeviceData.getDefaultInstance();
      }

      public PipelinesMessage.DeviceData build() {
        PipelinesMessage.DeviceData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PipelinesMessage.DeviceData buildPartial() {
        PipelinesMessage.DeviceData result = new PipelinesMessage.DeviceData(this);
        result.deviceId_ = deviceId_;
        result.port_ = port_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PipelinesMessage.DeviceData) {
          return mergeFrom((PipelinesMessage.DeviceData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PipelinesMessage.DeviceData other) {
        if (other == PipelinesMessage.DeviceData.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getPort().isEmpty()) {
          port_ = other.port_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PipelinesMessage.DeviceData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PipelinesMessage.DeviceData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string deviceId = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object port_ = "";
      /**
       * <code>string port = 2;</code>
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          port_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string port = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string port = 2;</code>
       */
      public Builder setPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }
      /**
       * <code>string port = 2;</code>
       */
      public Builder setPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        port_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 3;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 3;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DeviceData)
    }

    // @@protoc_insertion_point(class_scope:DeviceData)
    private static final PipelinesMessage.DeviceData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PipelinesMessage.DeviceData();
    }

    public static PipelinesMessage.DeviceData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceData>
        PARSER = new com.google.protobuf.AbstractParser<DeviceData>() {
      public DeviceData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DeviceData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceData> getParserForType() {
      return PARSER;
    }

    public PipelinesMessage.DeviceData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PipelineQueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PipelineQuery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    java.util.List<PipelinesMessage.PipelineDevices> 
        getPipelineDevicesList();
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    PipelinesMessage.PipelineDevices getPipelineDevices(int index);
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    int getPipelineDevicesCount();
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    java.util.List<? extends PipelinesMessage.PipelineDevicesOrBuilder> 
        getPipelineDevicesOrBuilderList();
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    PipelinesMessage.PipelineDevicesOrBuilder getPipelineDevicesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PipelineQuery}
   */
  public  static final class PipelineQuery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PipelineQuery)
      PipelineQueryOrBuilder {
    // Use PipelineQuery.newBuilder() to construct.
    private PipelineQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PipelineQuery() {
      pipelineDevices_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PipelineQuery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pipelineDevices_ = new java.util.ArrayList<PipelinesMessage.PipelineDevices>();
                mutable_bitField0_ |= 0x00000001;
              }
              pipelineDevices_.add(
                  input.readMessage(PipelinesMessage.PipelineDevices.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pipelineDevices_ = java.util.Collections.unmodifiableList(pipelineDevices_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PipelinesMessage.internal_static_PipelineQuery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PipelinesMessage.internal_static_PipelineQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PipelinesMessage.PipelineQuery.class, PipelinesMessage.PipelineQuery.Builder.class);
    }

    public static final int PIPELINEDEVICES_FIELD_NUMBER = 1;
    private java.util.List<PipelinesMessage.PipelineDevices> pipelineDevices_;
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    public java.util.List<PipelinesMessage.PipelineDevices> getPipelineDevicesList() {
      return pipelineDevices_;
    }
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    public java.util.List<? extends PipelinesMessage.PipelineDevicesOrBuilder> 
        getPipelineDevicesOrBuilderList() {
      return pipelineDevices_;
    }
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    public int getPipelineDevicesCount() {
      return pipelineDevices_.size();
    }
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    public PipelinesMessage.PipelineDevices getPipelineDevices(int index) {
      return pipelineDevices_.get(index);
    }
    /**
     * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
     */
    public PipelinesMessage.PipelineDevicesOrBuilder getPipelineDevicesOrBuilder(
        int index) {
      return pipelineDevices_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pipelineDevices_.size(); i++) {
        output.writeMessage(1, pipelineDevices_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pipelineDevices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pipelineDevices_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PipelinesMessage.PipelineQuery)) {
        return super.equals(obj);
      }
      PipelinesMessage.PipelineQuery other = (PipelinesMessage.PipelineQuery) obj;

      boolean result = true;
      result = result && getPipelineDevicesList()
          .equals(other.getPipelineDevicesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPipelineDevicesCount() > 0) {
        hash = (37 * hash) + PIPELINEDEVICES_FIELD_NUMBER;
        hash = (53 * hash) + getPipelineDevicesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PipelinesMessage.PipelineQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PipelinesMessage.PipelineQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PipelinesMessage.PipelineQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PipelinesMessage.PipelineQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PipelinesMessage.PipelineQuery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PipelineQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PipelineQuery)
        PipelinesMessage.PipelineQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PipelinesMessage.internal_static_PipelineQuery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PipelinesMessage.internal_static_PipelineQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PipelinesMessage.PipelineQuery.class, PipelinesMessage.PipelineQuery.Builder.class);
      }

      // Construct using PipelinesMessage.PipelineQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPipelineDevicesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (pipelineDevicesBuilder_ == null) {
          pipelineDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pipelineDevicesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PipelinesMessage.internal_static_PipelineQuery_descriptor;
      }

      public PipelinesMessage.PipelineQuery getDefaultInstanceForType() {
        return PipelinesMessage.PipelineQuery.getDefaultInstance();
      }

      public PipelinesMessage.PipelineQuery build() {
        PipelinesMessage.PipelineQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PipelinesMessage.PipelineQuery buildPartial() {
        PipelinesMessage.PipelineQuery result = new PipelinesMessage.PipelineQuery(this);
        int from_bitField0_ = bitField0_;
        if (pipelineDevicesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pipelineDevices_ = java.util.Collections.unmodifiableList(pipelineDevices_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pipelineDevices_ = pipelineDevices_;
        } else {
          result.pipelineDevices_ = pipelineDevicesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PipelinesMessage.PipelineQuery) {
          return mergeFrom((PipelinesMessage.PipelineQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PipelinesMessage.PipelineQuery other) {
        if (other == PipelinesMessage.PipelineQuery.getDefaultInstance()) return this;
        if (pipelineDevicesBuilder_ == null) {
          if (!other.pipelineDevices_.isEmpty()) {
            if (pipelineDevices_.isEmpty()) {
              pipelineDevices_ = other.pipelineDevices_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePipelineDevicesIsMutable();
              pipelineDevices_.addAll(other.pipelineDevices_);
            }
            onChanged();
          }
        } else {
          if (!other.pipelineDevices_.isEmpty()) {
            if (pipelineDevicesBuilder_.isEmpty()) {
              pipelineDevicesBuilder_.dispose();
              pipelineDevicesBuilder_ = null;
              pipelineDevices_ = other.pipelineDevices_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pipelineDevicesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPipelineDevicesFieldBuilder() : null;
            } else {
              pipelineDevicesBuilder_.addAllMessages(other.pipelineDevices_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PipelinesMessage.PipelineQuery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PipelinesMessage.PipelineQuery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PipelinesMessage.PipelineDevices> pipelineDevices_ =
        java.util.Collections.emptyList();
      private void ensurePipelineDevicesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pipelineDevices_ = new java.util.ArrayList<PipelinesMessage.PipelineDevices>(pipelineDevices_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PipelinesMessage.PipelineDevices, PipelinesMessage.PipelineDevices.Builder, PipelinesMessage.PipelineDevicesOrBuilder> pipelineDevicesBuilder_;

      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public java.util.List<PipelinesMessage.PipelineDevices> getPipelineDevicesList() {
        if (pipelineDevicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pipelineDevices_);
        } else {
          return pipelineDevicesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public int getPipelineDevicesCount() {
        if (pipelineDevicesBuilder_ == null) {
          return pipelineDevices_.size();
        } else {
          return pipelineDevicesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public PipelinesMessage.PipelineDevices getPipelineDevices(int index) {
        if (pipelineDevicesBuilder_ == null) {
          return pipelineDevices_.get(index);
        } else {
          return pipelineDevicesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder setPipelineDevices(
          int index, PipelinesMessage.PipelineDevices value) {
        if (pipelineDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.set(index, value);
          onChanged();
        } else {
          pipelineDevicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder setPipelineDevices(
          int index, PipelinesMessage.PipelineDevices.Builder builderForValue) {
        if (pipelineDevicesBuilder_ == null) {
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.set(index, builderForValue.build());
          onChanged();
        } else {
          pipelineDevicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder addPipelineDevices(PipelinesMessage.PipelineDevices value) {
        if (pipelineDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.add(value);
          onChanged();
        } else {
          pipelineDevicesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder addPipelineDevices(
          int index, PipelinesMessage.PipelineDevices value) {
        if (pipelineDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.add(index, value);
          onChanged();
        } else {
          pipelineDevicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder addPipelineDevices(
          PipelinesMessage.PipelineDevices.Builder builderForValue) {
        if (pipelineDevicesBuilder_ == null) {
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.add(builderForValue.build());
          onChanged();
        } else {
          pipelineDevicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder addPipelineDevices(
          int index, PipelinesMessage.PipelineDevices.Builder builderForValue) {
        if (pipelineDevicesBuilder_ == null) {
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.add(index, builderForValue.build());
          onChanged();
        } else {
          pipelineDevicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder addAllPipelineDevices(
          java.lang.Iterable<? extends PipelinesMessage.PipelineDevices> values) {
        if (pipelineDevicesBuilder_ == null) {
          ensurePipelineDevicesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pipelineDevices_);
          onChanged();
        } else {
          pipelineDevicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder clearPipelineDevices() {
        if (pipelineDevicesBuilder_ == null) {
          pipelineDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pipelineDevicesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public Builder removePipelineDevices(int index) {
        if (pipelineDevicesBuilder_ == null) {
          ensurePipelineDevicesIsMutable();
          pipelineDevices_.remove(index);
          onChanged();
        } else {
          pipelineDevicesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public PipelinesMessage.PipelineDevices.Builder getPipelineDevicesBuilder(
          int index) {
        return getPipelineDevicesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public PipelinesMessage.PipelineDevicesOrBuilder getPipelineDevicesOrBuilder(
          int index) {
        if (pipelineDevicesBuilder_ == null) {
          return pipelineDevices_.get(index);  } else {
          return pipelineDevicesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public java.util.List<? extends PipelinesMessage.PipelineDevicesOrBuilder> 
           getPipelineDevicesOrBuilderList() {
        if (pipelineDevicesBuilder_ != null) {
          return pipelineDevicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pipelineDevices_);
        }
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public PipelinesMessage.PipelineDevices.Builder addPipelineDevicesBuilder() {
        return getPipelineDevicesFieldBuilder().addBuilder(
            PipelinesMessage.PipelineDevices.getDefaultInstance());
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public PipelinesMessage.PipelineDevices.Builder addPipelineDevicesBuilder(
          int index) {
        return getPipelineDevicesFieldBuilder().addBuilder(
            index, PipelinesMessage.PipelineDevices.getDefaultInstance());
      }
      /**
       * <code>repeated .PipelineDevices pipelineDevices = 1;</code>
       */
      public java.util.List<PipelinesMessage.PipelineDevices.Builder> 
           getPipelineDevicesBuilderList() {
        return getPipelineDevicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PipelinesMessage.PipelineDevices, PipelinesMessage.PipelineDevices.Builder, PipelinesMessage.PipelineDevicesOrBuilder> 
          getPipelineDevicesFieldBuilder() {
        if (pipelineDevicesBuilder_ == null) {
          pipelineDevicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PipelinesMessage.PipelineDevices, PipelinesMessage.PipelineDevices.Builder, PipelinesMessage.PipelineDevicesOrBuilder>(
                  pipelineDevices_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pipelineDevices_ = null;
        }
        return pipelineDevicesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PipelineQuery)
    }

    // @@protoc_insertion_point(class_scope:PipelineQuery)
    private static final PipelinesMessage.PipelineQuery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PipelinesMessage.PipelineQuery();
    }

    public static PipelinesMessage.PipelineQuery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PipelineQuery>
        PARSER = new com.google.protobuf.AbstractParser<PipelineQuery>() {
      public PipelineQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PipelineQuery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PipelineQuery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PipelineQuery> getParserForType() {
      return PARSER;
    }

    public PipelinesMessage.PipelineQuery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PipelineDevices_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PipelineDevices_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PipelineQuery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PipelineQuery_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&proto/messages/pipelines-message.proto" +
      "\"G\n\017PipelineDevices\022\022\n\npipelineId\030\001 \001(\t\022" +
      " \n\013devicesData\030\002 \003(\0132\013.DeviceData\";\n\nDev" +
      "iceData\022\020\n\010deviceId\030\001 \001(\t\022\014\n\004port\030\002 \001(\t\022" +
      "\r\n\005value\030\003 \001(\t\":\n\rPipelineQuery\022)\n\017pipel" +
      "ineDevices\030\001 \003(\0132\020.PipelineDevicesb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PipelineDevices_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PipelineDevices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PipelineDevices_descriptor,
        new java.lang.String[] { "PipelineId", "DevicesData", });
    internal_static_DeviceData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeviceData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceData_descriptor,
        new java.lang.String[] { "DeviceId", "Port", "Value", });
    internal_static_PipelineQuery_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PipelineQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PipelineQuery_descriptor,
        new java.lang.String[] { "PipelineDevices", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
