deployment:
  app: device-service-app
  name: device-service
  replicaCount: 1
  port: 8080
  containers:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 6Gi
  tenant:
    id:
      attribute:
        key: tenant-id
  mongo:
    uri: mongodb://mongo-0.mongo:27017/
    database: device-service
  projectId: single-system-dev
  kafka:
    topic:
      forSave: device-data-for-save
      sendingData:
        device: device-sending-data
        port: port-sending-data
    bootstrap:
      servers: 10.8.15.224:9092
  executionService:
    address:
      host: 10.8.7.76
      port: 9099
  subscription:
    deviceData: data-from-device-sub
    pipelineAdding: pipeline-adding-sub
    pipelineDeleting: pipeline-deleting-sub
service:
  port: 8080
actuator:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: '*'
env:
  JDK_JAVA_OPTIONS: "-Xmx3584M"